version: "3"
services:
  dns:
    container_name: dohcloudflared
    image: rdcarrera/doh-cloudflared:latest
    restart: unless-stopped
    user: root
    networks:
      dnsn:
        ipv4_address: 172.22.0.11
    environment:
      DNS_PORT: 53
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp"
    - "80:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'D3f1n3S0meP4ssW0rdH3r3'
      PIHOLE_DNS: '172.22.0.11'
      DNS1: '172.22.0.11'
    volumes:
    - 'pihole-config:/etc/pihole/'
    - 'pihole-dnsmasq:/etc/dnsmasq.d/'
    dns:
    - 172.22.0.11
    cap_add:
    - NET_ADMIN
    restart: unless-stopped
    privileged: true
    networks:
      dnsn:
        ipv4_address: 172.22.0.10
networks:
  dnsn:
    driver: bridge
    ipam:
        config:
        - subnet: 172.22.0.0/24
volumes:
    pihole-config: {}
    pihole-dnsmasq: {}